### ISSUE TITLE
UUID data type not yet supported

### ISSUE THREAD

**Issue by sanmadjack** [mongo-dart/bson#19]
BSON type 3 is not implemented yet according to the comments. I'd be happy to do the work, what needs to be done?

**Comment by Pacane** [comment]
Are you looking to use UUID or the object type specifically?

**Comment by sanmadjack** [comment]
I'm looking to store uuids in binary using the mongo dart package.

**Comment by Pacane** [comment]
May I ask why you want to store them in binary instead of strings?

**Comment by sanmadjack** [comment]
Everything I've read says that's the recommended method for storing UUIDs. Supposedly performance is better, and mongo has some limited understanding of uuid in binary (The exact extent of this is unclear to me though). Do you have information to the contrary?

**Comment by giorgiofran** [comment]
Uuid implemented in last version of Bson. I close the issue.
