### ISSUE TITLE
makeByteList method of BsonBinary instance can't be used independently

### ISSUE THREAD

**Issue by lvscar** [mongo-dart/bson#25]
The error message is 
> NoSuchMethodError: The getter 'length' was called on null. Receiver: null Tried calling: length

Pub version for bson package : 0.3.1

Core stack code location:
bson-0.3.1/lib/src/types/binary.dart 86:20                BsonBinary.makeByteList

**Comment by lvscar** [comment]
After digging into the code implementation , I found the expected result of makeByteList depended on a previous makeHexString method execution

**Comment by giorgiofran** [comment]
BsonBinary implementation has changed, so maybe that you no more need to use makeByeList. As it is an old issue I close it. Feel free to reopen if needed.
