### ISSUE TITLE
Convert Endianness references to Endian

### ISSUE THREAD

**Issue by jbaxe2** [mongo-dart/bson#27]
The Endianness class (from dart:typed_data) was renamed in Dart 2 to Endian, and corresponding UPPERCASE_CONSTANTS were renamed to lowercast_constant versions.  These Dart 2 changes should be updated in this package.

**Comment by sestegra** [comment]
Starting from dart 2.0.0-dev.69.2

**Comment by lvscar** [comment]
Please merge [the PR](https://github.com/mongo-dart/bson/pull/28) as soon as possible . Let's embrace the coming of dart2.

**Comment by vadimtsushko** [comment]
Thank you for contribution
