### ISSUE TITLE
Support for EJSON parse and stringify (relaxed mode, etc)

### ISSUE THREAD

**Issue by sachaarbonel** [mongo-dart/bson#29]
Hi guys thank's for this great library. Would it be possible to match the node library and add support for EJSON parse and stringify. For example :

```dart
import 'package:bson/ejson.dart';;
var text = '{ "int32": { "$numberInt": "10" } }';
 
// prints { int32: { [String: '10'] _bsontype: 'Int32', value: '10' } }
print(ejson.parse(text, { relaxed: false }));
 
// prints { int32: 10 }
print(ejson.parse(text));
```

**Comment by 926** [comment]
Hi everyone,
Support for this would be most welcome.

**Comment by giorgiofran** [comment]
No plans for now.
What do you need exactly? Maybe that we can evaluate what to do, at least initally on a reduced set of types.

**Comment by donadev** [comment]
I was looking for a way to parse the EJSON data returned from Atlas Functions called from a Flutter app, but according to the documentation, you have to do it by hand, am I missing something?

**Comment by giorgiofran** [comment]
I check If I can do some simple improvement. Do you have some test case?

**Comment by giorgiofran** [comment]
Hi all, support for ejson (still apha version) has been published (ver 5.0.0-1.0.dev). If there is anyone that can help me with testing I would appreciate.

**Comment by giorgiofran** [comment]
New beta is out with support for ejson v2.

**Comment by giorgiofran** [comment]
Release 5.0.0 with support for ejson v2 has been released.
