### ISSUE TITLE
Purpose of clientMode in ObjectId 

### ISSUE THREAD

**Issue by Tokenyet** [mongo-dart/bson#31]
Just a curious about what's the usage of `ObjectId(clientMode: true)`?  A similar method as `Mongoose` create it without inserting to real database? Can't find any comments or clue in the source code, so I ask here. Hope someone know the concept could share with 😄

**Comment by giorgiofran** [comment]
I don't know the logic behind the `clientMode` flag. I haven't yet had time to investigate.
Maybe the original creator of the package can answer this question.
At present, it generates the binary code of the `ObjectId` in a different way when the flag is set:
```
if (clientMode) {
      var s = '${getOctet(seconds)}${getOctet(Statics.RandomId)}'
          '${getOctet(Statics.nextIncrement)}';
      return BsonBinary.fromHexString(s);
    } else {
      return BsonBinary(12)
        ..writeInt(seconds, endianness: Endian.big)
        ..writeInt(Statics.RandomId)
        ..writeInt(Statics.nextIncrement, endianness: Endian.big);
    }
```

**Comment by giorgiofran** [comment]
Client mode has been remove in release 5.0.0
